name: Build Fastfiles on Tag

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build-patch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Build fastfiles
        run: |
          make build

      - name: Upload fastfiles to release
        uses: softprops/action-gh-release@v2
        with:
          fail_on_unmatched_files: true
          files: build/*.zip
